#!/bin/bash

#output=$(./compile.sh)
output=$(java_compile)
if [[ "$output" != *"Compiled successfuly!"* ]]
then
	echo "$output"
	exit
fi

lib="lib"
out="out"

# cd out

class="Main"
if [ -z $1 ]
then
	owo_print "Running on default class \"$class\""
else
	owo_print "Running on class \"$1\""
	class=$1
fi

# java -cp "$out:$lib/*" $class
# $1 will be the $class; the others will be given as parameters
java -cp "$out:$lib/*" $@
